{{- if .Values.telemetry -}}
{{- if .Values.telemetry.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "cost-analyzer.telemetry.name" . }}
  labels:
    {{ include "cost-analyzer.commonLabels" . | nindent 4 }}
type: "kubernetes.io/Opaque"
data:
  archera-api-key: {{ default "" .Values.telemetry.archeraAPIKey | b64enc | quote }}
{{- end }}
{{- end }}
